### PR TITLE
Fix <AddressInput /> component

### PR DESCRIPTION
**Pull request by yagopv**
The AddressInput component is removing the network prefix on paste. This is because the changes in the major 1.0.0 so we remove the specific change and use a workaround to get the same visual behavior

We fix the disabled state as well on selects as did not match the designs

### CODE REVIEW

**Comment by iamacook** [comment]
Nice to see all the changes you've made. Have you checked all of these in new inputs across `safe-react`?

**Comment by yagopv** [comment]
> Nice to see all the changes you've made. Have you checked all of these in new inputs across `safe-react`?

Nope, didn't check. But we made a major release (1.0.0) just in case for not autoupdate safe-react and break things

**Comment by iamacook** [comment]
> I kept the properties we had and only added two mandatory new ones (name, label) in the Select field so should be ok with minor changes. I integrated it in the Transaction Builder and it was straightforward

Should be fine then. It would be nice if this was tested, however. We often make small changes to components and it could break things. cc @francovenica

**Comment by yagopv** [comment]
yeah of course, that's because is a major release. We need this for the transaction builder now, but for integrating it in safe-react a more deep look should be taken

**Review by dasanra — APPROVED** [review]

**Pull request merged**
