### PR TITLE
Configure testing environments for pull requests

### PR DESCRIPTION
**Pull request by luarx**
To make it easier to test new pull requests

### CODE REVIEW

**Comment by rmeissner** [comment]
Will you add the required aws key?

**Comment by luarx** [comment]
I am still configuring it :D 
The best test for this task is to have a real PR

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr19--safereactcomponents.review.gnosisdev.com/app

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr19--safereactcomponents.review.gnosisdev.com/app

**Comment by mikheevm** [comment]
https://github.com/gnosis/safe-react-components/pull/12 should we close this one then?

**Comment by luarx** [comment]
I think so, as from now on every commit on a pull request will run a new build

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr19--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr19--safereactcomponents.review.gnosisdev.com

**Pull request merged**
