### PR TITLE
FixedDialog component styles

### LINKED ISSUE #118: Can't edit FixedDialog background color
This issue was detected in `safe-react@v3.5.0`

Problem:

We use FixedDialog component to show the legal disclaimer when using the apps. It uses a fixed background color that can't be edited:

We should approach this to modal styles with transparent background and box shadow

### PR DESCRIPTION
**Pull request by alongoni**
Closes #118 
Related to https://github.com/gnosis/safe-react/issues/2189
image

Backgound removed and styles fixes.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr119--safereactcomponents.review.gnosisdev.com

**Review by fernandomg — APPROVED** [review]

**Review by dasanra — APPROVED** [review]

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr119--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr119--safereactcomponents.review.gnosisdev.com

**Comment by katspaugh** [comment]
Please pull from development and update the snapshots.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr119--safereactcomponents.review.gnosisdev.com

**Pull request merged**
