### PR TITLE
Accordion component

### PR DESCRIPTION
**Pull request by alongoni**
Closes https://github.com/gnosis/safe-react-components/issues/84.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr85--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr85--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr85--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr85--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr85--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr85--safereactcomponents.review.gnosisdev.com

**Review by nicosampler — APPROVED** [review]

**Review by dasanra — APPROVED** [review]

**Pull request merged**
