### PR TITLE
Add hover state to icons

### LINKED ISSUE #134: Add Hover event to icon-buttons
Related to https://github.com/gnosis/safe-react/pull/2433

According with the design, we have to add a hover state to the icons that works as buttons.
https://app.zeplin.io/project/5b83b4fa75f90943c86ed14f/screen/5e7394b2dc79fdbde6d4d1f8
https://app.zeplin.io/project/5b83b4fa75f90943c86ed14f/screen/5f5b904b0faf6c76b20961f3
image

### PR DESCRIPTION
**Pull request by alongoni**
Closes #134 

image

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr135--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr135--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr135--safereactcomponents.review.gnosisdev.com

**Review by katspaugh — APPROVED** [review]
Nice!

**Review by matextrem — APPROVED** [review]

**Pull request merged**
