### PR TITLE
Add table component

### PR DESCRIPTION
**Pull request by alongoni**
Related to https://github.com/gnosis/safe-react-components/issues/27

Next Steps:

- [x] Add Collapsable feature
- [x] Add stories

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by nicosampler** [comment]
Functionality is done, @alongoni will work on styles. but we can start working in safe-react with this components for the new TXs page.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by nicosampler** [comment]
@mikheevm ready for review

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr30--safereactcomponents.review.gnosisdev.com

**Comment by dasanra** [comment]
Sortable table is not working for me now. You should review this before merging

**Comment by nicosampler** [comment]
This was implemented in safe-react repo.

**Pull request closed without merging**
