### PR TITLE
Feature: EthHasInfo add showHash property

### PR DESCRIPTION
**Pull request by nicosampler**
- [x] It is no possible not to render the hash but render the Identicon. That's why I added the `showHash` prop.
- [x] Adding a `border-radius` of 50%  was breaking some SVGs. If that is needed should be customized when the Component is being used.

### CODE REVIEW

**Review by katspaugh — APPROVED** [review]
Nice!

**Comment by liliya-soroka** [comment]
@nicosampler , could you provide more details about where and how it influences on the app ? It really hard to understand how  and where to test. Why do we change it ? Is it related to some issue?

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr120--safereactcomponents.review.gnosisdev.com

**Comment by mikheevm** [comment]
I just noticed some errors in tests:
https://github.com/gnosis/safe-react-components/blob/development/src/dataDisplay/Icon/icon.stories.tsx#L15-L22
https://github.com/gnosis/safe-react-components/blob/development/src/dataDisplay/FixedIcon/fixedIcon.stories.tsx

how did this get through?

**Review by alongoni — APPROVED** [review]

**Comment by nicosampler** [comment]
@liliya-soroka, this is a stand-alone component. Not directly related to safe-react repository. 
So far we are not requiring manual testing here as the outcome will impact the tickets in safe-react, so testing the tickets in safe-react would cover these components.

**Comment by katspaugh** [comment]
I've filed https://github.com/gnosis/safe-react-components/issues/122 to fix the tests.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr120--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr120--safereactcomponents.review.gnosisdev.com

**Pull request merged**
