### PR TITLE
(Fix) remove background color and center icons from Tabs component

### LINKED ISSUE #86: Set transparent background for Tabs component

### PR DESCRIPTION
**Pull request by alongoni**
Closed #86 
image

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr87--safereactcomponents.review.gnosisdev.com

**Review by fernandomg — CHANGES_REQUESTED** [review]
there's a `border-bottom` prop, that must be removed:

image

**Comment by fernandomg** [comment]
> there's a `border-bottom` prop, that must be removed:
> 
> <kbd></kbd>

hmm... now that I see the requirements, it seems to be required. But I'm not sure if the width is correct (@alongoni, thoughts?)

image

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr87--safereactcomponents.review.gnosisdev.com

**Review by fernandomg — APPROVED** [review]
:100:

**Review by dasanra — APPROVED** [review]

**Review by nicosampler — APPROVED** [review]

**Pull request merged**
