### PR TITLE
(Fix) Button styles

### PR DESCRIPTION
**Pull request by alongoni**
- [x] Increase the text-size to 16px (in order keep align with the design). This maybe a breaking change.

image
- [x] Remove letter-spacing

- [x] Add shadows
image

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr108--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr108--safereactcomponents.review.gnosisdev.com

**Review by fernandomg — APPROVED** [review]

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr108--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr108--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr108--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr108--safereactcomponents.review.gnosisdev.com

**Review by fernandomg — APPROVED** [review]

**Pull request merged**
