### PR TITLE
Add Alert Component

### PR DESCRIPTION
**Pull request by yagopv**
Resolves https://github.com/gnosis/safe-react/issues/2501

We are integrating an Alert component for being able to use for resolving the above task. Figma designs inside

### CODE REVIEW

**Review by iamacook — COMMENTED** [review]
Why export a component that already exists in MUI?

**Comment by iamacook** [comment]
> For changing the color and showing proper docs in Storybook

You can use the colours from the theme directly, no?

**Comment by iamacook** [comment]
> Ah, you mean why I'm not using the component directly in safe-react from material-ui right? Without any change in safe-react-components

Yes, we have this component library installed there.

**Comment by yagopv** [comment]
For me is perfectly fine to use it in a direct way but I thought the point of the component library was at the end expose what are we able to use in our apps and document it properly (storybook). Right now the Alert is as simple as you can see but can grow as design requirements can change.

I would like to see one place with all our components. But yes, understand completely your point. For me is a little confusing to have material, here and there and perhaps in my mind in the future to only import from the component library in safe-react. But I see lot of direct imports checking now.

For me is ok but what do you think about this @dasanra as we talk about adding it to the library

@katspaugh what are you thought around this ? Should we avoid simple wrappers around material components?

**Comment by yagopv** [comment]
yeah totally. Sometimes i feel dirty making this wrappers but on the other hand there are a lot of imports from material ui in our projects and i feel like not controlling what are our real components

**Comment by yagopv** [comment]
About the alpha, yes. We are on material 4 and all 4 versions for the material-ui/lab are alphas

**Comment by katspaugh** [comment]
@yagopv I think you're making a good point about importing all components from a single library in a Safe App.

Obviously, safe-react-components by no means is or aims to be a full UI framework. But I think it's fine to add components that are needed by apps, on a precedent basis. Even if they are just wrappers.

Although, in this particular case, isn't this alert going to be used in safe-react itself, which already uses MUI directly quite extensively?

**Comment by yagopv** [comment]
In this case the Alerts are only going to be used in safe-react yes. So I can use them there without wrappers (I need to add @material-ui/lab btw). Are you ok with that @dasanra ??

So in safe-react-components we should only add components really useful for the safe-apps and if we have a new ui requirement for safe-web entirely covered by material-ui we should develop it in the safe-web project directly right? If is like that for me is clarified 👻

**Comment by iamacook** [comment]
> In this case the Alerts are only going to be used in safe-react yes. So I can use them there without wrappers (I need to add @material-ui/lab btw).

@material-ui/lab is already present in safe-react

**Comment by mikheevm** [comment]
I wanted to ask precisely the same question as Aaron did. I don't think we need to reinvent the wheel and add a wrapper over a wrapper. Just use the theme instead

**Comment by yagopv** [comment]
One thing around the theme I would like to comment is about doesn't make sense to make it [compatible with material-ui](https://mui.com/customization/default-theme)?,  because right now we have 2 Providers involved

https://github.com/gnosis/safe-react/blob/9c613653e5ff6c55467da9280dff295485b2a87a/src/components/Providers/index.tsx#L20-L30

If we export a material ui compatible theme in the component library then some safe-apps only need that for the UI and (probably) can use even material 5.

But perhaps i'm missing something here 😥

**Comment by mikheevm** [comment]
it needs to be edited in the mui theme defined in safe-react:
https://github.com/gnosis/safe-react/blob/4edc0b79d19c412203cbbd370330ce4a62f0e83e/src/components/Root/index.tsx#L11

**Comment by yagopv** [comment]
yeah, I mean ... We have 2 themes, one imported from the component library and the other created and defined in safe-react:

```
import { theme as styledTheme } from '@gnosis.pm/safe-react-components'
import theme from 'src/theme/mui'
```

For me perhaps should exist only the material ui one (src/theme/mui) and being used and exported from the component library as we use material ui in all the projects. But we can talk about this offline or in the daily doesn't matter because perhaps I'm missing the point and this PR is about other topic 😁

**Comment by mikheevm** [comment]
> For me perhaps should exist only the material ui one (src/theme/mui) and being used and exported from the component library as we use material ui in all the projects. But we can talk about this offline or in the daily doesn't matter because perhaps I'm missing the point and this PR is about other topic 😁

Yes, you are right. This library was not well thought out and now theming is a mess.

Could you please elaborate on "this PR is about other topic"? This PR created a wrapper component to edit some colors which could be edited in the theme on the safe-react side

**Comment by yagopv** [comment]
Yes and I'm going to follow the recommendation with which I totally agree and close this PR for continuing the work in https://github.com/gnosis/safe-react/pull/3404. 

The other topic for me is to have some frontend team discussion about what we want to do with the component library and how to handle this situations

**Pull request closed without merging**
