### PR TITLE
Feature: Add Tooltip component

### PR DESCRIPTION
**Pull request by nicosampler**
This component is required in SR for tx-v2.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr92--safereactcomponents.review.gnosisdev.com

**Review by matextrem — APPROVED** [review]

**Review by alongoni — COMMENTED** [review]
Looks Good! 
We can add a placement options via props. E.g.: top, right, bottom, left

**Comment by nicosampler** [comment]
> Looks Good!
> We can add a placement options via props. E.g.: top, right, bottom, left

we already have it.

**Review by alongoni — APPROVED** [review]

**Review by fernandomg — APPROVED** [review]
looks nice

**Pull request merged**
