### PR TITLE
IconText styles

### LINKED ISSUE #83: [Components] IconText
Allow setting different colors for Icon and for text. Actually it receives one prop "color" and it assigns the same color in both components.

### PR DESCRIPTION
**Pull request by alongoni**
Closes #83 
Now we can set individually the icon and text colors.
image

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr124--safereactcomponents.review.gnosisdev.com

**Review by katspaugh — APPROVED** [review]
Cool!

Please pull from development and update the snapshots once #125 is merged. This'll fix the tests.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr124--safereactcomponents.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr124--safereactcomponents.review.gnosisdev.com

**Review by katspaugh — APPROVED** [review]
Thanks Agu!

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr124--safereactcomponents.review.gnosisdev.com

**Comment by katspaugh** [comment]
I've tested that it works and doesn't break anything. 👍

**Pull request merged**
