### PR TITLE
refactor: add interfaces for theme

### PR DESCRIPTION
**Pull request by PaulRBerg**
Changelog:

+ Add interfaces for the theme object in `styled-components.d.ts`
+ Modify the `Button`, `ButtonLink`, `Icon`, `IconText`, `Loader`, `Text`, `Title` components to follow the new interfaces that can be imported directly from `styled-components`

I don't think this would cause any disruption to existing users, so this could be either a minor or a patch version upgrade.

### CODE REVIEW

**Comment by PaulRBerg** [comment]
> I really like the idea of defining the types in a .d.ts file!

I only did what they said in the [styled-components docs](https://styled-components.com/docs/api#typescript).

> What do you think about splitting this file into the same categories we are splitting components?

Yeah that sounds good. You mean pulling each interface out and defining it in its own bespoke `.d.ts` file, or implementing it directly in the component file?

**Comment by nicosampler** [comment]
> pulling each interface out and defining it in its own bespoke .d.ts file
I think this one is the best option

**Comment by PaulRBerg** [comment]
I'll do it tonight, it shouldn't take more than 5-10 mins.

It'd be great to have this PR merged sooner than later so I can deduplicate the interfaces from my own repo.

**Comment by nicosampler** [comment]
Yes. But it will take some time to deploy it to NPM.

In the meantime, you can install it from Github (pointing to the commit) instead of NPM. We are following that strategy until we get the new release deployed.

**Comment by PaulRBerg** [comment]
Sorted!

> In the meantime, you can install it from Github (pointing to the commit) instead of NPM

Ah, cool.

**Comment by mikheevm** [comment]
Hey @PaulRBerg , could you please explain why you did this change?

> Modify the Button, ButtonLink, Icon, IconText, Loader, Text, Title components to follow the new interfaces that can be imported directly from styled-components

why would you want to import it directly from `styled-components`? It's not a part of the library

did you want to avoid `keyof theme['colors']` things?

**Comment by PaulRBerg** [comment]
The app wouldn't build without those changes.

**Comment by mikheevm** [comment]
What error did you have?

**Comment by nicosampler** [comment]
> The app wouldn't build without those changes.

The app should build fine. 

We think the only change we need to do is replace the Theme by DefaultInterface, to set the types in Props.

For example:

```
import styled, { DefaultTheme } from 'styled-components';

type Props = {
  children: any;
  size: keyof DefaultTheme['text']['size'];
  color?: keyof DefaultTheme['colors'];
  strong?: boolean;
  center?: boolean;
};
```

**Comment by PaulRBerg** [comment]
> What error did you have?

I just reverted back two commits in the past, modified only the "typings" folder and ran the `yarn tsc` command. [Here's a GitHub gist](https://gist.github.com/PaulRBerg/160014220f398f3b1526167debe02004) with all the errors I got.

> We think the only change we need to do is replace the Theme by DefaultInterface, to set the types in Props.

I haven't checked whether this would be enough, but I think using the interface fields themselves, instead of `keyof`, is safer.

**Comment by nicosampler** [comment]
@PaulRBerg 
I could not reproduce the errors you are having. Are these errors coming from `safe-react-components` of they come from your safe-app consuming `safe-react-components`?

Also, moving `Theme` Types into `styled.d.ts` has a problem, when you want to consume the components in another project, it does not autocomplete the type props.

For example:
`<Text size="" />` It won't suggest you about the values for `size` prop.

**Comment by mikheevm** [comment]
@PaulRBerg 
Screenshot 2020-06-03 at 17 49 19

This is what I get on `development` branch with fresh dependencies installation. Without dependencies, I get an output similar to yours

**Comment by PaulRBerg** [comment]
> I could not reproduce the errors you are having. Are these errors coming from `safe-react-components` of they come from your safe-app consuming `safe-react-components`?

From this repository. The errors I got had nothing to do with my Safe app.

> Also, moving `Theme` Types into `styled.d.ts` has a problem, when you want to consume the components in another project, it does not autocomplete the type props.

Not sure I follow. There's no `styled.d.ts` file in my PR.

If others want to consume the theme, it has to be exported here and imported and extended from in the external project.

**Comment by PaulRBerg** [comment]
I ran a second test now and the project doesn't compile without my changes to `keyof`. Instead of reverting two commits in the past, I modified the `Title/index.tsx` file from HEAD:

```ts
import { Theme } from '../../theme';

type Props = {
  children: string;
  size: keyof Theme['title']['size'];
  withoutMargin?: boolean;
};
```

Running `yarn tsc` gives me this output in the terminal:

```
yarn run v1.22.4
$ /Users/paulrberg/Workspace/Pad/safe-react-components/node_modules/.bin/tsc
src/dataDisplay/Title/index.tsx:46:31 - error TS2532: Object is possibly 'undefined'.

46   font-size: ${({ theme }) => theme.title.size.xs.fontSize};
                                 ~~~~~~~~~~~~~~~~~~~

src/dataDisplay/Title/index.tsx:47:33 - error TS2532: Object is possibly 'undefined'.

47   line-height: ${({ theme }) => theme.title.size.xs.lineHeight};
                                   ~~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

**Comment by PaulRBerg** [comment]
> This is what I get on `development` branch with fresh dependencies installation. Without dependencies, I get an output similar to yours

I have my dependencies installed. As explained in my last commit, this is a compiler issue. Just modify the `Title` component and see what's happening with `keyof Theme['title']['size']`.

**Comment by PaulRBerg** [comment]
Maybe it's worth it to set up a CI pipeline? That would unequivocally prove what's going on.

**Comment by mikheevm** [comment]
> I have my dependencies installed. As explained in my last commit, this is a compiler issue. Just modify the Title component and see what's happening with keyof Theme['title']['size'].

Sorry @PaulRBerg, I still don't get it. What should I modify to get the errors? I tried it again with latest typescript compiler version (3.9.5) and don't have any problems. Could you please cleanup this branch/create a new one with the changes you made and where the project doesn't build?

> Maybe it's worth it to set up a CI pipeline? That would unequivocally prove what's going on.
Good idea, will work on it

**Comment by mikheevm** [comment]
@PaulRBerg https://github.com/gnosis/safe-react-components/pull/12 It builds with no errors

**Comment by nicosampler** [comment]
To summarize:
* There is no problem running the types. (try with branch development or master). Noone in our team is having problems with it. So I assume it's something regarding your branch or machine. 

* We are giving types to DefaultTheme like so:
```
import { Theme } from '../theme';

declare module "styled-components" {  
  export interface DefaultTheme extends Theme {}
}
```
But then, we are not typing components trough `DefaultTheme` because when the project is built, it does not export these typings. TS compiler does not include in the build .d.ts files. 
That's why we are typing like so:
```
import theme, { Theme } from '../../theme';
...
export interface Props {
  size: keyof Theme['buttons']['size'];
}
```
I'll close this PR, do not hesitate to talk with us if you are still having problems trying to compile with TS.

**Comment by PaulRBerg** [comment]
Ah, guys, we've been talking past each other.

> The app wouldn't build without those changes.

When I said this, I was specifically referring to the build **on this PR branch**. That is, when I removed `extends Theme` and defined the types under `DefaultTheme`, the app wouldn't build without changing all components that were using `keyof Theme[]`.

The upstream `development` is perfectly fine and I never had any issues with it.

> But then, we are not typing components trough DefaultTheme because when the project is built, it does not export these typings.

Riiight! I didn't know about this. It seems to be a noted problem in the TypeScript world: https://github.com/Microsoft/TypeScript/issues/5112.

---

Given that there must be a way to include the `.d.ts` files in the build, my knee-jerk reaction was to propose reopening this PR, but I saw this: https://github.com/styled-components/styled-components-website/issues/447 and I now understand why you maintain your theme with `DefaultTheme extends Theme`.

Generally, I think there's quite a few things left to do by styled-component to enhance the documentation and provide more clarity on TypeScript usage, but that's out of scope for this thread.

Thanks again and sorry for wasting your time!

**Pull request closed without merging**
